// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ediqerrocenadkcgcsmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkaXFlcnJvY2VuYWRrY2djc21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzEyNzgsImV4cCI6MjA3MjQ0NzI3OH0.LSCow54gYHZcKdaCfSmMEAuttjwmc9_ppK--OL06vTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});